### ISSUE TITLE
Build Configuration Failed 

### ISSUE THREAD

**Issue by GibsonRuitiari** [c0de-wizard/grade-catalog-demo#1]
Hi @c0de-wizard , it is me again (I swear this is not a witch-hunt).  First, thank you so much for this project, it serves as an awesome reference. I was using your project to learn how to go about managing dependencies using gradle catalog, unfortunately the build is failing with a weird error. Similarly, the error can be reproduced in your other project [Stargazer]; for some reason android-studio cannot
find the reference of the android-app-plugin.
```
Script compilation error:

  Line 2:     `android-app-plugin`
              ^ Unresolved reference: `android-app-plugin`
```
If you do manage to look into this issue, thank you so much in advance.

**Comment by thomaskioko** [comment]
Hi @GibsonRuitiari It's all good. 🙂  I forgot to commit this file and that's why it wasn't compiling. I have added it and updated some dependencies. Should be good not. Let me know if you run into any other issues.
